apiVersion: v1
kind: Service
metadata:
  name: echo-app
  namespace: t2o-dev
  labels:
    app: echo-app
spec:
  ports:
    - port: 1323
      targetPort: 1323
  selector:
    app: echo-app

---
apiVersion: apps/v1
kind: Deployment #对象类型
metadata:
  name: echo-app #名称
  namespace: t2o-dev
  labels:
    app: echo-app #标注
spec:
  replicas: 1 #运行容器的副本数，修改这里可以快速修改分布式节点数量
  selector:
    matchLabels:
      app: echo-app
  template:
    metadata:
      labels:
        app: echo-app
    spec:
      containers: #docker容器的配置
        - name: echo-app
          image: registry.cn-hangzhou.aliyuncs.com/sonicmoving/debug-service:1.0.2 # pull镜像的地址 ip:prot/dir/images:tag
          imagePullPolicy: IfNotPresent #pull镜像时机
          ports:
            - containerPort: 1323 #容器对外开放端口



